package com.solbeg.sas.perfmgmnt.dto.llm;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * Response body from the OpenRouter Chat Completions API.
 *
 * @param id      unique completion identifier
 * @param choices list of generated choices (typically one)
 * @param usage   token usage statistics for cost tracking
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ChatCompletionResponse(
        String id,
        List<Choice> choices,
        Usage usage
) {

    /**
     * A single generated completion choice.
     *
     * @param index        zero-based index of this choice
     * @param message      the generated assistant message
     * @param finishReason why generation stopped (e.g. {@code "stop"}, {@code "length"})
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public record Choice(
            int index,
            Message message,
            @JsonProperty("finish_reason") String finishReason
    ) {

        /**
         * The assistant message generated by the model.
         *
         * @param role    always {@code "assistant"} in a response
         * @param content the generated text
         */
        @JsonIgnoreProperties(ignoreUnknown = true)
        public record Message(String role, String content) {}
    }

    /**
     * Token usage statistics. Useful for cost monitoring.
     *
     * @param promptTokens     tokens consumed by the input (system + user messages)
     * @param completionTokens tokens generated in the response
     * @param totalTokens      sum of prompt and completion tokens
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public record Usage(
            @JsonProperty("prompt_tokens") int promptTokens,
            @JsonProperty("completion_tokens") int completionTokens,
            @JsonProperty("total_tokens") int totalTokens
    ) {}
}
